export const menus = {
  "2025-11-10": {
    week: "Semana 10 - 14 Noviembre",
    menu: [
      {
        day: "Lunes 10",
        soup: "Sopa de Caracolitos con Huevo",
        entree: "Brocoli Zanahoria, Choclo Pimenton y Mix de Repollo",
        main1: "Milanesa de Pollo con Arroz Ciboulette o Budin de Acelga Zanahoria",
        main2: "Merluza Apanada con Arroz Ciboulette o Budin de Acelga Zanahoria",
        vegetarian: "Curry de Garbanzos con Arroz Ciboulette o Budin de Acelga Zanahoria",
        hypocaloric: "Bowl Wraps de Atun",
        dessert: "Medialunas Rellenas, Bavarois de Frambuesa, Fruta Natural y Jalea",
      },
      {
        day: "Martes 11",
        soup: "Crema de Arvejas con Jamon",
        entree: "Lechuga Rabanitos, Pepino Perejil y Tomate Poroto Verde",
        main1: "Pechuga de Pollo con Tallarines Espinaca o Humita en Olla",
        main2: "Vacuno a la Cacerola con Tallarines Espinaca o Humita en Olla",
        vegetarian: "Pastel de Choclo con Carne de Soya",
        hypocaloric: "Bowl Tomate Relleno (Pollo)",
        dessert: "Turron de Vino, Mote con Ciruela, Fruta Natural y Jalea",
      },
      {
        day: "Miércoles 12",
        soup: "Sopa de Pollo con Verduras y Huevo",
        entree: "Apio con Aceitunas, Ensalada China y Ensalada de Cochayuyo",
        main1: "Panita Lyonesa con Papas Doradas o Tortillon de Acelga",
        main2: "Tomatican de Vacuno con Papas Doradas o Tortillon de Acelga",
        vegetarian: "Hamburguesa de Soya Atomatada con Papas Doradas o Tortillon de Acelga",
        hypocaloric: "Bowl Criollo (Vacuno)",
        dessert: "Arroz con Leche, Natilla Tiramisu, Fruta Natural y Jalea",
      },
      {
        day: "Jueves 13",
        soup: "Crema de Verduras",
        entree: "Ensalada Cebolla Asada, Lechuga con Pasas y Tomate Cebollin",
        main1: "Pollo al Romero con Espirales Mediterraneos o Guiso de Porotos Verdes",
        main2: "Lentejas Guisadas con Huevo Duro",
        vegetarian: "Lentejas Guisadas con Huevo Duro",
        hypocaloric: "Bowl Wraps Porotos Negros y Vegetales (Vacuno)",
        dessert: "Bavarois de Naranja, Flan de Caramelo, Fruta Natural y Jalea",
      },
      {
        day: "Viernes 14",
        soup: "Sopa de Carne con Semola y Huevo",
        entree: "Ensalada Porotos Negros con Salsa Verde, Repollo Blanco Zanahoria y Tomate Lechuga",
        main1: "Lomo de Cerdo a las Finas Hierbas con Papas Mayo o Guiso de Verduras a la Siciliana",
        main2: "Trutro de Pollo Asado con Papas Mayo o Guiso de Verduras Siciliana",
        vegetarian: "Hamburguesa de Soya Napolitana con Papas Mayo o Guiso de Verduras a la Siciliana",
        hypocaloric: "Bowl Natural con Salmon",
        dessert: "Mousse de Platano, Torta de Durazno Manjar, Fruta Natural y Jalea",
      },
    ],
  },
  "2025-11-17": {
    week: "Semana 17 - 21 Noviembre",
    menu: [
        {
            day: "Lunes 17",
            soup: "Crema de Champiñones",
            entree: "Coliflor Brocoli, Habas Cebolla y Lechuga",
            main1: "Budin de Atun con Pure de Papas o Choclo a la Crema",
            main2: "Hamburguesa Arvejada con Pure de Papas o Choclo a la Crema",
            vegetarian: "Hamburguesa de Soya con Pure de Papas o Choclo a la Crema",
            hypocaloric: "Bowl Fondo de Alcachofa Reina (Pollo)",
            dessert: "Queque Marmol, Bavarois de Limon, Fruta Natural y Jalea",
          },
          {
            day: "Martes 18",
            soup: "Sopa de Pollo con Arroz y Huevo",
            entree: "Ensalada de Cebolla Asada, Lechuga con Crutones y Tomate Poroto Verde",
            main1: "Aji de Gallina con Arroz Perla o Ratatouille",
            main2: "Harira con Arroz Perla o Ratatouille",
            vegetarian: "Humita en Hoja",
            hypocaloric: "Bowl Atun Jardinera",
            dessert: "Flan de Bocado, Fruta Natural y Jalea",
          },
          {
            day: "Miércoles 19",
            soup: "Crema de Choclo",
            entree: "Ceviche de Champiñones, Apio con Aceitunas y Ensalada China",
            main1: "Espirales con Salsa Alfredo de Pollo o Acelga a la Crema",
            main2: "Tomatican de Cerdo con Espirales Tricolor o Acelga a la Crema",
            vegetarian: "Zapallo Italiano Relleno con Soya y Arroz",
            hypocaloric: "Bowl Criollo (Vacuno)",
            dessert: "Arroz con Leche, Manjar y Jalea",
          },
          {
            day: "Jueves 20",
            soup: "Sopa de Carne con Arroz y Huevo",
            entree: "Ensalada Chilena, Lechuga con Crutones y Pepino Perejil",
            main1: "Pollo a la Plancha con Arroz Primavera",
            main2: "Porotos con Mazamorra y Longaniza",
            vegetarian: "Hamburguesa Vegana con Arroz Primavera",
            hypocaloric: "Bowl de Ensaladas con Pechuga de Pollo",
            dessert: "Flan de Caramelo, Fruta Natural y Jalea",
          },
          {
            day: "Viernes 21",
            soup: "Crema de Coliflor Parmesano",
            entree: "Lechuga y Repollo con Aceitunas",
            main1: "Chuleta de Cerdo al Ajillo con Pure de Papas o Tortillon de Acelga",
            main2: "Salmon a las Finas Hierbas con Pure de Papas o Tortillon de Acelga",
            vegetarian: "Papa Rellena con Queso",
            hypocaloric: "Bowl Wraps de Pollo. Queso y Vegetales",
            dessert: "Torta de Chocolate Manjar, Fruta Natural y Jalea",
          },
    ]
  }
};
